name: CI/CD Pipeline for Hutieugo-WordPress

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test-wordpress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build WordPress image (for testing)
        run: |
          docker build -t wordpress-test -f Dockerfile .

  deploy:
    needs: [build-and-test-wordpress]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push WordPress image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hutieugo-wordpress:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/hutieugo-wordpress
            echo "Pulling latest WordPress image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hutieugo-wordpress:latest
            echo "Waiting for Traefik to be ready..."
            until docker ps | grep -q web-traefik-1; do
              echo "Waiting for Traefik to be up..."
              sleep 5
            done
            echo "Starting WordPress containers..."
            docker compose -f docker-compose.yml up -d wordpress
            echo "Checking running containers..."
            docker compose -f docker-compose.yml ps
